### ISSUE TITLE
Little bug with prefix command

### ISSUE THREAD

**Issue by Junifil744** [AtlasC0R3/drop-discord#1]
**Describe the bug**
If you do prefix command without saying any prefix, it will result in a error

**To Reproduce**
1. Say !prefix

**Expected behavior**
Nothing of course i just wanted to test it

**Screenshots**
Im new to github i dont know how to put a screenshot

**Additional context**
It happened when a friend though you needed to say !prefix, send THEN say the prefix

**Comment by AtlasC0R3** [comment]
Seeing the `error.txt` you sent me on Discord, I don't *think* it's a Drop issue, I'm thinking it's either a Discord.py issue or an HTTP issue. Either way, I'll see what I can do.
